
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// CLI datasource (db push / migrate / studio). Prefer the direct / session-pooler
// connection (DIRECT_URL); fall back to DATABASE_URL. A literal placeholder keeps
// `prisma generate` working during the Vercel build even before env vars are set
// (generate never connects — it only needs a non-empty string here).
const cliDatabaseUrl =
  process.env.DIRECT_URL ||
  process.env.DATABASE_URL ||
  "postgresql://user:pass@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: cliDatabaseUrl,
  },
});
