
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // CLI only (db push / migrate / studio) — use the direct / session-pooler
    // connection. The app runtime uses DATABASE_URL from prisma/schema.prisma.
    url: env("DIRECT_URL"),
  },
});
